listVersion = "1"

[[projects]]
projectName = "Project Alpha"
dnsName = "ALPHA.com"
description = "Alpha is a security project."
ips = [ "192.168.1.1", "192.168.1.2", "192.168.1.3" ]
ports = [ 80, 443, 22 ]

[[projects]]
projectName = "Project Beta"
dnsName = "BETA.com"
description = "Beta is a data analytics project."
ips = [ "10.0.0.1", "10.0.0.2" ]
ports = [ 8_080, 3_306, 5_432 ]

[[projects]]
projectName = "Project Gamma"
description = "Gamma is a cloud infrastructure project."
ips = [ "172.16.0.1", "172.16.0.2" ]
ports = [ 21, 25, 110 ]

[[projects]]
projectName = "portquiz"
dnsName="portquiz.net"
description = "portquiz"
ips = [ "35.180.139.74", "8.8.4.4" ]
ports = [ 80, 8_080, 666, 22 ]
